/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL8eBgttibf5g= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL8eBgttibf5g= >>
// ----------- >>
public class listaGraduatoria {
    // ----------- << attribute.annotations@AAAAAAGL8eChAdotxoY= >>
    // ----------- >>
    private String {unique} descrizione;

    private String {unique} getDescrizione() {
        return descrizione;
    }

    private void setDescrizione(String {unique} descrizione) {
        this.descrizione = descrizione;
    }

// ----------- << class.extras@AAAAAAGL8eBgttibf5g= >>
// ----------- >>
}