/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL8Y9kMu3BS7w= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL8Y9kMu3BS7w= >>
// ----------- >>
public class anagrafica {
// ----------- << class.extras@AAAAAAGL8Y9kMu3BS7w= >>
// ----------- >>
}