/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL7ampn2ChcM4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL7ampn2ChcM4= >>
// ----------- >>
public class anagrafica paziente {
    // ----------- << attribute.annotations@AAAAAAGL7ampn2CQECo= >>
    // ----------- >>
    private String nome;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CRj8o= >>
    // ----------- >>
    private String cognome;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CSzeU= >>
    // ----------- >>
    private String {unique} cf;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CTL84= >>
    // ----------- >>
    private Date dataNascita;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CUd9A= >>
    // ----------- >>
    private String luogoNascita;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CVAN0= >>
    // ----------- >>
    private String indirizzo;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CWLnE= >>
    // ----------- >>
    private String tel;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CXyVM= >>
    // ----------- >>
    private String email;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CaN5E= >>
    // ----------- >>
    private String anamnesiPregressa;

    private String getNome() {
        return nome;
    }

    private String getCognome() {
        return cognome;
    }

    private String {unique} getCf() {
        return cf;
    }

    private Date getDataNascita() {
        return dataNascita;
    }

    private String getLuogoNascita() {
        return luogoNascita;
    }

    private String getIndirizzo() {
        return indirizzo;
    }

    private String getTel() {
        return tel;
    }

    private String getEmail() {
        return email;
    }

    private String getAnamnesiPregressa() {
        return anamnesiPregressa;
    }

    private void setNome(String nome) {
        this.nome = nome;
    }

    private void setCognome(String cognome) {
        this.cognome = cognome;
    }

    private void setCf(String {unique} cf) {
        this.cf = cf;
    }

    private void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    private void setLuogoNascita(String luogoNascita) {
        this.luogoNascita = luogoNascita;
    }

    private void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    private void setTel(String tel) {
        this.tel = tel;
    }

    private void setEmail(String email) {
        this.email = email;
    }

    private void setAnamnesiPregressa(String anamnesiPregressa) {
        this.anamnesiPregressa = anamnesiPregressa;
    }

    // ----------- << method.annotations@AAAAAAGL7ampn2CgJpA= >>
    // ----------- >>
    public void Aggiungere get e set() {
    // ----------- << method.body@AAAAAAGL7ampn2CgJpA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL8MwyZXqxUYY= >>
    // ----------- >>
    public int eta() {
    // ----------- << method.body@AAAAAAGL8MwyZXqxUYY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGL7ampn2ChcM4= >>
// ----------- >>
}