/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL7ampn2CJpmA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL7ampn2CJpmA= >>
// ----------- >>
public class cabina di regia extends Personale sanitario {
    /**
    * @param cfPaziente 
    * @param codOperazione
    */

    // ----------- << method.annotations@AAAAAAGL7ampn2CIqmE= >>
    // ----------- >>
    public Set<String> getListaEsami(String cfPaziente, String codOperazione) {
    // ----------- << method.body@AAAAAAGL7ampn2CIqmE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGL7ampn2CJpmA= >>
// ----------- >>
}