/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL7ampn2C7Y94= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL7ampn2C7Y94= >>
// ----------- >>
public enum ClasseAttesa {
    ClasseA,
    ClasseB,
    ClasseC,
    ClasseD;

// ----------- << enum.extras@AAAAAAGL7ampn2C7Y94= >>
// ----------- >>
}