/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL7ampn2C0cx4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL7ampn2C0cx4= >>
// ----------- >>
public class esame {
    // ----------- << attribute.annotations@AAAAAAGL7ampn2ClST8= >>
    // ----------- >>
    private String nome;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CmzXA= >>
    // ----------- >>
    private boolean completato;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2CpEww= >>
    // ----------- >>
    private int {Unique} CodiceEsame;

    private String getNome() {
        return nome;
    }

    private boolean isCompletato() {
        return completato;
    }

    private int {Unique} getCodiceEsame() {
        return CodiceEsame;
    }

    private void setNome(String nome) {
        this.nome = nome;
    }

    private void setCompletato(boolean completato) {
        this.completato = completato;
    }

    private void setCodiceEsame(int {Unique} CodiceEsame) {
        this.CodiceEsame = CodiceEsame;
    }

    // ----------- << method.annotations@AAAAAAGL7ampn2CrWGQ= >>
    // ----------- >>
    public String getNome() {
    // ----------- << method.body@AAAAAAGL7ampn2CrWGQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL7ampn2CtTKs= >>
    // ----------- >>
    public boolena getCompletato() {
    // ----------- << method.body@AAAAAAGL7ampn2CtTKs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL7ampn2CvJjY= >>
    // ----------- >>
    public String getPaziente() {
    // ----------- << method.body@AAAAAAGL7ampn2CvJjY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL7ampn2Cx6y8= >>
    // ----------- >>
    public String getCodiceOperazione() {
    // ----------- << method.body@AAAAAAGL7ampn2Cx6y8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL7ampn2Czy0c= >>
    // ----------- >>
    public void setCompletato() {
    // ----------- << method.body@AAAAAAGL7ampn2Czy0c= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGL7ampn2C0cx4= >>
// ----------- >>
}