/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL8YqejtPNEfs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL8YqejtPNEfs= >>
// ----------- >>
public class intervento {
    // ----------- << attribute.annotations@AAAAAAGL8YrlNdUpucM= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGL8Y04t9fOJHY= >>
    // ----------- >>
    private String descrizione;

    private int getId() {
        return id;
    }

    private String getDescrizione() {
        return descrizione;
    }

    private void setId(int id) {
        this.id = id;
    }

    private void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    // ----------- << method.annotations@AAAAAAGL8Y2gtNl8B7s= >>
    // ----------- >>
    public int getId() {
    // ----------- << method.body@AAAAAAGL8Y2gtNl8B7s= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL8Y3vY9pUFYc= >>
    // ----------- >>
    public String getDecrizione() {
    // ----------- << method.body@AAAAAAGL8Y3vY9pUFYc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGL8YqejtPNEfs= >>
// ----------- >>
}