/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL8ZIkEhAgxYk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL8ZIkEhAgxYk= >>
// ----------- >>
public class intevento {
    // ----------- << attribute.annotations@AAAAAAGL8ZJ+8xF9Hr0= >>
    // ----------- >>
    private int {unique} id;

    // ----------- << attribute.annotations@AAAAAAGL8eI1INt+nGg= >>
    // ----------- >>
    private String descrizione;

    // ----------- << attribute.annotations@AAAAAAGL8eYPgvf7O2w= >>
    // ----------- >>
    private void diagnosi;

    // ----------- << attribute.annotations@AAAAAAGL8ZMBAxHn054= >>
    // ----------- >>
    private String anamnesiProssima;

    // ----------- << attribute.annotations@AAAAAAGL8ZQ3jRLa5fM= >>
    // ----------- >>
    private classeAttesa tempoAttesa;

    // ----------- << attribute.annotations@AAAAAAGL8eavufqwo1A= >>
    // ----------- >>
    private void note;

    private int {unique} getId() {
        return id;
    }

    private String getDescrizione() {
        return descrizione;
    }

    private void getDiagnosi() {
        return diagnosi;
    }

    private String getAnamnesiProssima() {
        return anamnesiProssima;
    }

    private classeAttesa getTempoAttesa() {
        return tempoAttesa;
    }

    private void getNote() {
        return note;
    }

    private void setId(int {unique} id) {
        this.id = id;
    }

    private void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    private void setDiagnosi(void diagnosi) {
        this.diagnosi = diagnosi;
    }

    private void setAnamnesiProssima(String anamnesiProssima) {
        this.anamnesiProssima = anamnesiProssima;
    }

    private void setTempoAttesa(classeAttesa tempoAttesa) {
        this.tempoAttesa = tempoAttesa;
    }

    private void setNote(void note) {
        this.note = note;
    }

// ----------- << class.extras@AAAAAAGL8ZIkEhAgxYk= >>
// ----------- >>
}