/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL7ampn2CjeDU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL7ampn2CjeDU= >>
// ----------- >>
public class lista operatoria {
    // ----------- << attribute.annotations@AAAAAAGL7ampn2Ci3z0= >>
    // ----------- >>
    private void Attribute1;

    public void getAttribute1() {
        return Attribute1;
    }

    public void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

// ----------- << class.extras@AAAAAAGL7ampn2CjeDU= >>
// ----------- >>
}