/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Diagrammi di classe;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGL7ampn2B3YCM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGL7ampn2B3YCM= >>
// ----------- >>
public abstract class Personale sanitario {
    // ----------- << attribute.annotations@AAAAAAGL7ampn2Buirk= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2BvfqU= >>
    // ----------- >>
    private String Cognome;

    // ----------- << attribute.annotations@AAAAAAGL7ampn2Bwtec= >>
    // ----------- >>
    private String {unique readOnly} matricola;

    private String getNome() {
        return Nome;
    }

    private String getCognome() {
        return Cognome;
    }

    private String {unique readOnly} getMatricola() {
        return matricola;
    }

    private void setNome(String Nome) {
        this.Nome = Nome;
    }

    private void setCognome(String Cognome) {
        this.Cognome = Cognome;
    }

    private void setMatricola(String {unique readOnly} matricola) {
        this.matricola = matricola;
    }

    // ----------- << method.annotations@AAAAAAGL7ampn2By84c= >>
    // ----------- >>
    public String getNome() {
    // ----------- << method.body@AAAAAAGL7ampn2By84c= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL7ampn2B06nM= >>
    // ----------- >>
    public String getCognome() {
    // ----------- << method.body@AAAAAAGL7ampn2B06nM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGL7ampn2B2rbU= >>
    // ----------- >>
    public String getMatricola() {
    // ----------- << method.body@AAAAAAGL7ampn2B2rbU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGL7ampn2B3YCM= >>
// ----------- >>
}